name: Deploy Specific Folders to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy specific folders to S3
      run: |
        aws s3 sync ./website/images/ s3://${{ secrets.S3_BUCKET_NAME }}/
        aws s3 sync ./website/sitefiles/ s3://${{ secrets.S3_BUCKET_NAME }}/

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/website/images/*" "/website/sitefiles/*"
